In [43]:
import numpy as np
import pandas as pd

In [44]:
dataset = pd.read_csv("D:\Data.csv")

In [45]:
dataset

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Aggreate Independent and dependent variables

In [46]:
x = dataset[['Country','Age','Salary']].values

In [47]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [48]:
y = dataset[['Purchased']]

In [49]:
y

  Purchased
0        No
1       Yes
2        No
3        No
4       Yes
5       Yes
6        No
7       Yes
8        No
9       Yes

In [50]:
from sklearn.impute import SimpleImputer

In [51]:
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')

In [52]:
imputer = imputer.fit(x[:,1:3])

In [53]:
x[:,1:3] = imputer.transform(x[:,1:3])

In [54]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_encoder_x = LabelEncoder()

In [ ]:
x[:,0] = label_encode_x.fit_transform(x[:,0])

In [83]:
label_encoder_y = LabelEncoder()

In [84]:
y = label_encode_y.fit_transform(y)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [85]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [59]:
from sklearn.preprocessing import OneHotEncoder

In [60]:
onehotencoder = OneHotEncoder()

In [61]:
x = onehotencoder.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()

In [62]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [63]:
from sklearn.model_selection import train_test_split

In [73]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [74]:
x_train

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [75]:
x_test

array([[0., 1., 0.],
       [0., 1., 0.]])

In [76]:
from sklearn.preprocessing import StandardScaler

In [77]:
sc_x = StandardScaler()

In [78]:
x_train = sc_x.fit_transform(x_train)

In [81]:
x_test = sc_x.transform(x_test)

In [86]:
x_test

array([[-1.        ,  2.64575131, -0.77459667],
       [-1.        ,  2.64575131, -0.77459667]])

In [87]:
x_train

array([[-1.        ,  2.64575131, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667]])